Traceback (most recent call last):
  File "/usr/share/miniconda/envs/sasktran2-dev-build/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/share/miniconda/envs/sasktran2-dev-build/lib/python3.11/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/miniconda/envs/sasktran2-dev-build/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/miniconda/envs/sasktran2-dev-build/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/share/miniconda/envs/sasktran2-dev-build/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda/envs/sasktran2-dev-build/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda/envs/sasktran2-dev-build/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import sasktran2 as sk
import numpy as np

config = sk.Config()

model_geometry = sk.Geometry1D(cos_sza=0.6,
                                solar_azimuth=0,
                                earth_radius_m=6372000,
                                altitude_grid_m=[0, 1000, 500, 2000],
                                interpolation_method=sk.InterpolationMethod.LinearInterpolation,
                                geometry_type=sk.GeometryType.Spherical)

------------------

----- stdout -----
[2024-07-12 15:19:52.066] [critical] Invalid altitude grid: must be strictly increasing
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mRuntimeError[0m                              Traceback (most recent call last)
Cell [0;32mIn[2], line 6[0m
[1;32m      2[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m
[1;32m      4[0m config [38;5;241m=[39m sk[38;5;241m.[39mConfig()
[0;32m----> 6[0m model_geometry [38;5;241m=[39m [43msk[49m[38;5;241;43m.[39;49m[43mGeometry1D[49m[43m([49m[43mcos_sza[49m[38;5;241;43m=[39;49m[38;5;241;43m0.6[39;49m[43m,[49m
[1;32m      7[0m [43m                                [49m[43msolar_azimuth[49m[38;5;241;43m=[39;49m[38;5;241;43m0[39;49m[43m,[49m
[1;32m      8[0m [43m                                [49m[43mearth_radius_m[49m[38;5;241;43m=[39;49m[38;5;241;43m6372000[39;49m[43m,[49m
[1;32m      9[0m [43m                                [49m[43maltitude_grid_m[49m[38;5;241;43m=[39;49m[43m[[49m[38;5;241;43m0[39;49m[43m,[49m[43m [49m[38;5;241;43m1000[39;49m[43m,[49m[43m [49m[38;5;241;43m500[39;49m[43m,[49m[43m [49m[38;5;241;43m2000[39;49m[43m][49m[43m,[49m
[1;32m     10[0m [43m                                [49m[43minterpolation_method[49m[38;5;241;43m=[39;49m[43msk[49m[38;5;241;43m.[39;49m[43mInterpolationMethod[49m[38;5;241;43m.[39;49m[43mLinearInterpolation[49m[43m,[49m
[1;32m     11[0m [43m                                [49m[43mgeometry_type[49m[38;5;241;43m=[39;49m[43msk[49m[38;5;241;43m.[39;49m[43mGeometryType[49m[38;5;241;43m.[39;49m[43mSpherical[49m[43m)[49m

[0;31mRuntimeError[0m: Invalid input. Check log for more information

